### ISSUE TITLE
Page navigation is not correctly updated after filter is applied

### ISSUE THREAD

**Issue by solkaz** [MrSn0wy/fpps4.net#1]
When applying a filter to the compatibility list, the number of pages is not correctly updated and contains the old number of pages. This is updated when the user navigates to the next page (or attempts to)

When clicking a state filter:
https://github.com/MrSn0wy/fpps4.net/assets/10211603/79ad4301-1f47-4d9d-bbb6-13353251aac2

When typing in a query:

https://github.com/MrSn0wy/fpps4.net/assets/10211603/fae3fc61-896d-467b-b405-9d1db9560dd0

**Comment by MrSn0wy** [comment]
Heya, thank you for the (first) bug report!

I'll look into it, i thought that it should update when the games get updated but i guess i did something wrong xS

I will work on it in a moment and I'll give you an update when it's fixed.

**Comment by MrSn0wy** [comment]
it should be fixed now, if you hard refresh the page then it should be good.

**Comment by MrSn0wy** [comment]
i also made it so the manual page number is working xS
