### ISSUE TITLE
Missing IPv6 support

### ISSUE THREAD

**Issue by Mynacol** [MrSn0wy/fpps4.net#2]
fpps4.net lacks an AAAA DNS record, therefore it's not accessible over IPv6.
I believe you host at hostinger.com, which seem to be big proponents for IPv6. So you should be fine looking up the IPv6 at hostinger and inserting in your DNS registrar as an AAAA record.

**Comment by MrSn0wy** [comment]
Damn i didnt even know i had ipv6 with hostinger.
It should be added in the dns now, i can't test it myself because i don't have ipv6 with my 4g internet so please let me know if it works.

**Comment by Mynacol** [comment]
Unfortunately, the now inserted 2a02:4780:d:bbae::1 address is the wrong 
one. That one is for DNS, not for web content.

I'm honestly not sure if your service has an IPv6 address. The only 
public tutorial [1] shows you where to find the right IPv4, maybe next to 
it is the right IPv6 as well. Otherwise they might not offer IPv6 at this 
time.

Anyways, thanks for looking into this!

[1] 
https://support.hostinger.com/en/articles/4407303-where-to-find-the-a-record-of-your-hosting-account

**Comment by MrSn0wy** [comment]
it should be the ipv6 of my server, its in the overview of my vps.
can you show me what it displays when you try to connect to it?

**Comment by MrSn0wy** [comment]
it seems the management software i use for the sites doesn't support ipv6, im sorry but i wont be able to support it. Im planning on creating my own management solution but until then ipv6 isn't available.

**Comment by Mynacol** [comment]
Alright, thanks anyways for trying!

(The connection would just time out, which could be a closed firewall. 
Port 53 on this IPv6 however responded.)

**Comment by MrSn0wy** [comment]
Hey just wanted to let you know that IPv6 works now :D!

**Comment by Mynacol** [comment]
Hey, thanks for coming back to it. I see you use Cloudflare now.

**Comment by MrSn0wy** [comment]
Your welcome! And yes, a friend helped me set up cloudflare and i saw that they also give me a IPv6 address. I needed to immidiatly think of this issue xS.
